### ISSUE TITLE
feat: aws-sdk-go-v2 support

### ISSUE THREAD

**Issue by nabeken** [nabeken/aws-go-s3#63]
## TODO

- [x] Add a minio-based tests
- [x] Add aws-sdk-go-v2 support
- [x] Implement with `aws-sdk-go-v2`
  - [x] Pagination
  - [x] PreSigned URL
- [x] Add more tests
  - [x] ListObject w/ paginator
  - [x] DeleteObjects
  - [x] Presigned URL
 - [x] Write a note about the breaking changes
